TASK_CREATED = "TASK_CREATED"
TASK_UPDATED = "TASK_UPDATED"
TASK_MOVED = "TASK_MOVED"
TASK_DELETED = "TASK_DELETED"

COLUMN_CREATED = "COLUMN_CREATED"
COLUMN_UPDATED = "COLUMN_UPDATED"
COLUMN_DELETED = "COLUMN_DELETED"

AUTOMATION_RULE_CREATED = "AUTOMATION_RULE_CREATED"
AUTOMATION_RULE_UPDATED = "AUTOMATION_RULE_UPDATED"
AUTOMATION_RULE_DELETED = "AUTOMATION_RULE_DELETED"

INCOMING_TASK_RECEIVED = "INCOMING_TASK_RECEIVED"
INCOMING_TASK_VALIDATED = "INCOMING_TASK_VALIDATED"
INCOMING_TASK_REJECTED = "INCOMING_TASK_REJECTED"
INCOMING_TASK_PROCESSED = "INCOMING_TASK_PROCESSED"

AUTOMATION_TRIGGERED = "AUTOMATION_TRIGGERED"
NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
