TASK_CREATED = "TASK_CREATED"
TASK_UPDATED = "TASK_UPDATED"
TASK_MOVED = "TASK_MOVED"
TASK_DELETED = "TASK_DELETED"

INCOMING_TASK_RECEIVED = "INCOMING_TASK_RECEIVED"
INCOMING_TASK_VALIDATED = "INCOMING_TASK_VALIDATED"
INCOMING_TASK_REJECTED = "INCOMING_TASK_REJECTED"
INCOMING_TASK_PROCESSED = "INCOMING_TASK_PROCESSED"

AUTOMATION_TRIGGERED = "AUTOMATION_TRIGGERED"
NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
